"""
Trained machine-learning layer for POLAR-NAV AI.

HONEST LABELLING (build spec P2). Every model in this package is trained on data generated by
this repository's own physics environment, which is synthetic but physically structured. The
metrics reported anywhere in this package are therefore *simulated-environment* metrics. They
demonstrate that the training pipeline works, that the models learn the structure that is
present, and that they are scored against honest baselines. They are not, and are never claimed
to be, operational skill against satellite observations.

The three models, and what each one is actually for:

  sic_forecaster    post-processes the sea-ice analysis into a concentration forecast at a lead
                    time, scored against persistence, climatology and the existing semi-Lagrangian
                    physics forecast
  drift_residual    a residual corrector sitting on top of the RK4 iceberg momentum balance. It
                    is NOT a physics-informed neural network; it is a learned correction to a
                    physics core, which is a weaker and more honest claim
  growler_classifier  separates real small-ice radar returns from sea clutter, giving the radar
                    module a calibrated detection confidence instead of a hand-tuned threshold

Nothing in the physics path imports this package. If models/ is empty the whole system still
runs; see registry.ml_status().
"""
from __future__ import annotations

__all__ = [
    "dataset",
    "sic_forecaster",
    "drift_residual",
    "growler_classifier",
    "registry",
]
