"""
Learned sea-ice concentration forecaster.

WHAT THIS IS. A gradient-boosted regression tree that maps the ice and atmosphere analysis at
t0, plus a lead time, onto the concentration valid at t0 + lead. It is a statistical
post-processor of the analysis, in the same family as the model output statistics that national
weather services run on top of a dynamical forecast.

WHAT IT IS SCORED AGAINST. Three baselines, all evaluated on the same held-out test rows:

  persistence   today's concentration, carried forward unchanged. The bar every ice forecast
                has to clear, and at short lead times a genuinely hard one.
  climatology   the seasonal ice-edge ramp valid at the target time, with no knowledge of
                today's analysis at all.
  physics       SeaIceModel._advected_concentration, the existing semi-Lagrangian
                back-trajectory forecast blended toward climatology. This is the incumbent, and
                it is the baseline that matters.

Skill score is the usual 1 - RMSE_model / RMSE_baseline. A positive value means the model beats
that baseline; a negative value means it loses to it, and this module reports negative values
without softening them.

HONEST LABELLING (build spec P2). Trained on data generated by this repository's synthetic
physics environment. Every number produced here is simulated-environment skill, not operational
skill against OSI-SAF or AMSR2 retrievals.
"""
from __future__ import annotations

import math
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import joblib
import numpy as np
import sklearn
from sklearn.ensemble import HistGradientBoostingRegressor

from src.ml.dataset import SICDataset

# The 15 percent contour is the conventional ice edge, and it is the threshold that decides
# whether a route enters ice at all. Integrated Ice-Edge Error is the fraction of samples where
# the forecast and the verifying analysis disagree about which side of it they are on.
ICE_EDGE_THRESHOLD = 0.15

# Two candidate configurations. They are chosen on the validation window - a deep, slow-learning
# forest against a shallower, faster-learning one - so the validation split does real work rather
# than merely being reported. Early stopping is switched off deliberately: scikit-learn's
# internal early-stopping split is random, and a random split of a contiguous time window leaks
# exactly the way the module docstring in dataset.py describes.
CANDIDATE_HYPERPARAMETERS: Tuple[Dict[str, Any], ...] = (
    {
        "learning_rate": 0.06,
        "max_iter": 400,
        "max_leaf_nodes": 63,
        "min_samples_leaf": 40,
        "l2_regularization": 1.0,
    },
    {
        "learning_rate": 0.12,
        "max_iter": 220,
        "max_leaf_nodes": 31,
        "min_samples_leaf": 20,
        "l2_regularization": 0.1,
    },
)


def _rmse(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.sqrt(np.mean((np.asarray(a) - np.asarray(b)) ** 2)))


def _mae(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.mean(np.abs(np.asarray(a) - np.asarray(b))))


def _r2(pred: np.ndarray, truth: np.ndarray) -> float:
    truth = np.asarray(truth)
    denominator = float(np.sum((truth - truth.mean()) ** 2))
    if denominator <= 1e-12:
        return float("nan")
    return float(1.0 - np.sum((np.asarray(pred) - truth) ** 2) / denominator)


def _iiee(pred: np.ndarray, truth: np.ndarray) -> float:
    """Fraction of samples that disagree about being inside the 15 percent ice edge."""
    return float(np.mean((np.asarray(pred) >= ICE_EDGE_THRESHOLD) != (np.asarray(truth) >= ICE_EDGE_THRESHOLD)))


def _skill(rmse_model: float, rmse_baseline: float) -> float:
    """Murphy skill score. Positive beats the baseline, negative loses to it."""
    if rmse_baseline <= 1e-12:
        return float("nan")
    return float(1.0 - rmse_model / rmse_baseline)


class SICForecaster:
    """
    HistGradientBoostingRegressor over the analysis-state feature vector.

    Predictions are clipped to [0, 1] because concentration is an area fraction and a regressor
    has no idea that. Clipping is applied inside predict(), so every consumer gets a physically
    admissible value whether or not it remembers to check.
    """

    model_name = "sic_forecaster"

    def __init__(self, random_state: int = 26_059) -> None:
        self.random_state = random_state
        self.model: Optional[HistGradientBoostingRegressor] = None
        self.feature_names: Tuple[str, ...] = ()
        self.hyperparameters: Dict[str, Any] = {}
        self.metadata: Dict[str, Any] = {}

    # ------------------------------------------------------------------ fitting
    def fit(
        self,
        train: SICDataset,
        val: Optional[SICDataset] = None,
        candidates: Sequence[Dict[str, Any]] = CANDIDATE_HYPERPARAMETERS,
    ) -> "SICForecaster":
        """
        Fit on the training window, choosing hyperparameters on the validation window.

        With no validation set the first candidate is used unconditionally, which keeps the
        smoke-test path fast and still deterministic.
        """
        self.feature_names = tuple(train.feature_names)
        chosen: Optional[HistGradientBoostingRegressor] = None
        chosen_params: Dict[str, Any] = {}
        selection: List[Dict[str, Any]] = []
        best_rmse = math.inf

        for params in candidates:
            model = HistGradientBoostingRegressor(
                random_state=self.random_state, early_stopping=False, **params
            )
            model.fit(train.X, train.y)
            if val is None or len(val) == 0:
                chosen, chosen_params = model, dict(params)
                selection.append({"hyperparameters": dict(params), "val_rmse": None, "selected": True})
                break
            val_rmse = _rmse(np.clip(model.predict(val.X), 0.0, 1.0), val.y)
            selection.append({"hyperparameters": dict(params), "val_rmse": round(val_rmse, 6), "selected": False})
            if val_rmse < best_rmse:
                best_rmse, chosen, chosen_params = val_rmse, model, dict(params)

        if chosen is None:  # pragma: no cover - candidates is never empty in practice
            raise ValueError("No candidate hyperparameter set was supplied.")

        for entry in selection:
            entry["selected"] = entry["hyperparameters"] == chosen_params

        self.model = chosen
        self.hyperparameters = chosen_params
        self.metadata = {
            "sklearn_version": sklearn.__version__,
            "estimator": "HistGradientBoostingRegressor",
            "n_train_rows": int(len(train)),
            "n_val_rows": int(len(val)) if val is not None else 0,
            "train_window_hours": list(train.window_hours),
            "val_window_hours": list(val.window_hours) if val is not None else None,
            "feature_names": list(self.feature_names),
            "hyperparameter_selection": selection,
            "random_state": self.random_state,
        }
        return self

    # --------------------------------------------------------------- prediction
    def predict(self, X: np.ndarray) -> np.ndarray:
        """Concentration in [0, 1]. Raises if the model has not been fitted."""
        if self.model is None:
            raise RuntimeError("SICForecaster.predict called before fit or load.")
        X = np.asarray(X, dtype=np.float64)
        if X.ndim == 1:
            X = X.reshape(1, -1)
        return np.clip(self.model.predict(X), 0.0, 1.0)

    # --------------------------------------------------------------- evaluation
    def evaluate(self, ds: SICDataset) -> Dict[str, Any]:
        """
        Score the model and all three baselines on this split, overall and per lead time.

        Returned dictionary is JSON-serialisable so scripts/train.py can drop it straight into
        models/metrics.json.
        """
        pred = self.predict(ds.X)
        baselines = {
            "persistence": ds.persistence,
            "climatology": ds.climatology,
            "physics": ds.physics,
        }

        def score_block(mask: np.ndarray) -> Dict[str, Any]:
            truth = ds.y[mask]
            model_pred = pred[mask]
            block: Dict[str, Any] = {
                "n_samples": int(mask.sum()),
                "model": {
                    "rmse": round(_rmse(model_pred, truth), 5),
                    "mae": round(_mae(model_pred, truth), 5),
                    "r2": round(_r2(model_pred, truth), 5),
                    "iiee_fraction": round(_iiee(model_pred, truth), 5),
                },
                "baselines": {},
                "skill_score_vs": {},
            }
            model_rmse = _rmse(model_pred, truth)
            for name, values in baselines.items():
                base = values[mask]
                base_rmse = _rmse(base, truth)
                block["baselines"][name] = {
                    "rmse": round(base_rmse, 5),
                    "mae": round(_mae(base, truth), 5),
                    "r2": round(_r2(base, truth), 5),
                    "iiee_fraction": round(_iiee(base, truth), 5),
                }
                block["skill_score_vs"][name] = round(_skill(model_rmse, base_rmse), 5)
            return block

        per_lead: List[Dict[str, Any]] = []
        for lead in np.unique(ds.lead_hours):
            block = score_block(ds.lead_hours == lead)
            block["lead_hours"] = float(lead)
            per_lead.append(block)

        overall = score_block(np.ones(len(ds), dtype=bool))
        overall["window_hours"] = list(ds.window_hours)
        return {
            "n_samples": int(len(ds)),
            "ice_edge_threshold": ICE_EDGE_THRESHOLD,
            "overall": overall,
            "per_lead": per_lead,
            "note": (
                "Simulated-environment skill. Training and verification data are generated by "
                "this repository's synthetic sea-ice model, not by satellite retrievals."
            ),
        }

    # ------------------------------------------------------------- persistence
    def save(self, path: str | Path) -> Path:
        """Write the fitted estimator and its metadata to a single joblib artefact."""
        if self.model is None:
            raise RuntimeError("SICForecaster.save called before fit.")
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(
            {
                "model_name": self.model_name,
                "model": self.model,
                "feature_names": list(self.feature_names),
                "hyperparameters": self.hyperparameters,
                "metadata": self.metadata,
                "random_state": self.random_state,
            },
            path,
        )
        return path

    @classmethod
    def load(cls, path: str | Path) -> "SICForecaster":
        payload = joblib.load(Path(path))
        obj = cls(random_state=int(payload.get("random_state", 26_059)))
        obj.model = payload["model"]
        obj.feature_names = tuple(payload.get("feature_names", ()))
        obj.hyperparameters = dict(payload.get("hyperparameters", {}))
        obj.metadata = dict(payload.get("metadata", {}))
        return obj
